services:
    xapi_lrs.repository.activity.doctrine:
        class: XApi\Repository\Doctrine\Repository\ActivityRepository
        public: false
        arguments:
            - '@xapi_lrs.repository.mapped_statementObject'

    xapi_lrs.repository.state.doctrine:
        class: XApi\Repository\Doctrine\Repository\StateRepository
        public: false
        arguments:
            - '@xapi_lrs.repository.mapped_state'

    xapi_lrs.repository.statement.doctrine:
        class: XApi\Repository\Doctrine\Repository\StatementRepository
        public: false
        arguments:
            - '@xapi_lrs.repository.mapped_statement'
