services:
    xapi_lrs.event_listener.alternate_request_syntax:
        class: XApi\LrsBundle\EventListener\AlternateRequestSyntaxListener
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: -1 }

    xapi_lrs.event_listener.exception:
        class: XApi\LrsBundle\EventListener\ExceptionListener

    xapi_lrs.event_listener.serializer:
        class: XApi\LrsBundle\EventListener\SerializerListener
        arguments:
            - '@xapi_lrs.statement.serializer'
            - '@xapi_lrs.state.serializer'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: -3 }

    xapi_lrs.event_listener.version:
        class: XApi\LrsBundle\EventListener\VersionListener
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: -2 }
            - { name: 'kernel.event_listener', event: 'kernel.response' }
